subscription_alias_name   = "cr_subscription_test_99"
subscription_display_name = "CR 検証サブスクリプション 99"
billing_account_name      = "xxxxxxxxxxxx"
billing_profile_name      = "xxxxxxxxxxxx"
invoice_section_name      = "xxxxxxxxxxxx"
subscription_workload     = "DevTest"

resource_group_name       = "rg-vnet-sample"
location                  = "japaneast"
vnet_name                 = "vnet-sample"
subnet_name               = "subnet-sample"
